version: 2.1

commands:

jobs:

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Fetch and save the old pipeline ID (bucket name) responsible for the last release.
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/textfile.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - textfile.txt 
      - run: cat ~/textfile.txt

  deploy-frontend:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute bucket.yaml - Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
            --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
            --template-file cf_templates/template_bucket.yaml \
            --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://mybucket-${CIRCLE_WORKFLOW_ID:0:7} --delete

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
            --template-file cf_templates/template_cloudfront.yaml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="mybucket-${CIRCLE_WORKFLOW_ID:0:7}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - attach_workspace:
          at: ~/
      # - run: cat textfile.txt
      - run: cat ~/textfile.txt
      - run:
          name: Destroy the previous production version's S3 bucket and CloudFormation stack. 
          # Use $OldBucketID environment variable or mybucket644752792305 below.
          # Similarly, you can create and use $OldStackID environment variable in place of production-distro 
          command: |
            export OldBucketID=$(cat ~/textfile.txt)
            aws s3 rm "s3://${OldBucketID}" --recursive
            aws cloudformation delete-stack --stack-name stack-create-bucket-${OldBucketID:9:16}

workflows:
  aws-cd-workflow:
    jobs:
      - get_last_deployment_id
      - deploy-frontend
      - promote_to_production:
          requires: ['deploy-frontend']
      - clean_up_old_front_end:
          requires: ['promote_to_production']