version: 2.1

commands:

jobs:
  deploy-frontend:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute bucket.yaml - Create Cloudformation Stack
          command: |
            aws cloudformation create-stack \
            --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
            --template-body file://cf_templates/template_bucket.yaml \
            --region us-east-2 \
            --parameters file://cf_templates/params_bucket.json

workflows:
  aws-cd-workflow:
    jobs:
      - deploy-frontend